"""empty message

Revision ID: cca13f84f58b
Revises: 6808cba21049
Create Date: 2026-03-18 21:57:05.496900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca13f84f58b'
down_revision = '6808cba21049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.alter_column('apellido',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('contrasena')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrasena', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('apellido',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('admin')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
